### ISSUE TITLE
is it usable with LoRA fine-tuned whisper?

### ISSUE THREAD

**Issue by Boulaouaney** [sanchit-gandhi/whisper-jax#11]
curious to know if it runs well with a fine-tuned whisper model using PEFT?
is it possible to load it in int8?

**Comment by sanchit-gandhi** [comment]
Currently PEFT (and int8) is a Pytorch only library!

**Comment by Boulaouaney** [comment]
do you have any benchmarks in terms of which one would be faster? whisper-jax or inference from a LoRA (or AdaLoRA) whisper?

**Comment by sanchit-gandhi** [comment]
As far as I'm aware, using 8-bit quantisation is slower than vanilla fp16 in PyTorch. Here are the results from my benchmark on a Tesla T4 GPU:
<img width="507" alt="Screenshot 2023-03-09 at 19 00 15" src="https://user-images.githubusercontent.com/93869735/234020949-499f6906-50ee-4d86-a975-f1cc35a8e454.png">

Since Whisper JAX (fp16) is faster than Whisper PyTorch (fp16), it holds that it is also faster than 8-bit PyTorch for transcription time:
```
Whisper JAX (fp16) < Whisper PyTorch (fp16) < Whisper PyTorch (int8)
```

**Comment by Boulaouaney** [comment]
great! thanks for the info
