### ISSUE TITLE
Error when running on Google Colab (TPU)

### ISSUE THREAD

**Issue by seboslaw** [sanchit-gandhi/whisper-jax#13]
Hey,

I'm assuming this is a JAX issue, but I'm getting the following errors when trying to run the notebook on Google Colab:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-13-308fe9e13fe9>](https://pw2dauh3d9-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20230419-060138-RC00_525408879#) in <cell line: 1>()
----> 1 from whisper_jax import FlaxWhisperPipline
      2 import jax.numpy as jnp
      3 
      4 pipeline = FlaxWhisperPipline("openai/whisper-medium", dtype=jnp.bfloat16, batch_size=16)

4 frames
[/usr/local/lib/python3.9/dist-packages/flax/core/frozen_dict.py](https://pw2dauh3d9-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20230419-060138-RC00_525408879#) in <module>
     48 
     49 
---> 50 @jax.tree_util.register_pytree_with_keys_class
     51 class FrozenDict(Mapping[K, V]):
     52   """An immutable variant of the Python dict."""

AttributeError: module 'jax.tree_util' has no attribute 'register_pytree_with_keys_class'
```

I've already tried the hints mentions on JAX' Github page, but no success:

```
# tpu
import jax.tools.colab_tpu
jax.tools.colab_tpu.setup_tpu()

!pip install "jax<=0.3.25" "jaxlib<=0.3.25"

# gpu
import jax
jax.devices()
```

**Comment by ftcister** [comment]
this is because you are using `"jax<=0.3.25"` and in that version they dont have implemented yet the `'register_pytree_with_keys_class'` method, in the README.md of this repo Sanchit says `"Whisper JAX was tested using Python 3.9 and JAX version 0.4.5."`, so you have to upgrade yours jax version to 0.4.5 in colab

**Comment by sanchit-gandhi** [comment]
Unfortunately Colab uses the (outdated) TPU node architecture. If you update JAX to >=0.4.5 you'll see that there's a recommendation to swap to using Kaggle notebooks to get a TPU, since they use the newer TPU VM architecture. 

You can find the template Kaggle notebook here: https://www.kaggle.com/code/sgandhi99/whisper-jax-tpu

**Comment by seboslaw** [comment]
thx a lot for the quick response. I'm trying it on Kaggle now. Trying to get a feeling for what is the best value for money when it comes to processing units.
