### ISSUE TITLE
Specify the device when loading the pipeline

### ISSUE THREAD

**Issue by Boulaouaney** [sanchit-gandhi/whisper-jax#54]
is there a way to specify the device when loading the pipeline? it doesn't seem possible to pass the device id like you'd be able to do with the 🤗pipeline like:
`pipe = FlaxWhisperPipline("openai/whisper-large-v2", device=0, dtype=jnp.bfloat16, batch_size=16)`

I'm running a benchmark on multiple models/pipelines and whisper jax takes up all the VRAM available on the 2 GPUs I have (A100 80GB), which causes an OOM error when I try to process an audio file.
I'd like to have the possiblity to load whisper jax on device 0 and the other models on any other devices I have.

please recommend a way to do something like this

**Comment by sanchit-gandhi** [comment]
Note that the phenomenon of JAX using 90% of your GPU memory just to load the model is due to JAX's GPU memory allocation: https://jax.readthedocs.io/en/latest/gpu_memory_allocation.html

JAX doesn't actually require all of this memory, but blocks it out to prevent fragmentation.

You can set the device for `pmap`:
https://github.com/sanchit-gandhi/whisper-jax/blob/e2dddc98f8af5e5522341f61d5647cb31cd33ec7/whisper_jax/pipeline.py#L112-L114
with something as follows:
```python
# to use all accelerator devices
devices = jax.devices()
# to use 1 GPU
# devices = jax.devices()[0]

 self.p_generate = jax.pmap( 
     generate, "input_features", in_axes=(0, 0, None), out_axes=0, static_broadcasted_argnums=(3,), devices= devices
 ) 
```

See docs for more details: https://jax.readthedocs.io/en/latest/_autosummary/jax.pmap.html

**Comment by Boulaouaney** [comment]
This is very helpful! Thanks a lot
