### ISSUE TITLE
YouTube

### ISSUE THREAD

**Issue by peregilk** [sanchit-gandhi/whisper-jax#61]
Trying this on a TPU. While the transcription from YouTube seemed to be working fine when I first started the Gradio App, this seems to have stopped working. Anyone else seeing this issue?

**Comment by sanchit-gandhi** [comment]
Hey @peregilk - this looks like an issue with the PyTube package: https://github.com/pytube/pytube/issues/1553

I merged a PR that should fix this issue - instead of using PyTube, we use YouTube-DL: #67

You can run the updated app from [`app/app.py`](https://github.com/sanchit-gandhi/whisper-jax/blob/main/app/app.py) 

Note that you'll require the new Python package to download the YouTube data:
```
python3 -m pip install --force-reinstall https://github.com/yt-dlp/yt-dlp/archive/master.tar.gz
```

**Comment by ai792** [comment]
Check this to try fix this for Pytube: https://github.com/pytube/pytube/issues/1586#issuecomment-1531302928
