### ISSUE TITLE
Slower than faster-whisper (2x)

### ISSUE THREAD

**Issue by SinanAkkoyun** [sanchit-gandhi/whisper-jax#8]
Hi! I am running on WSL2 with an RTX 3090.
I've noticed that faster-whisper runs about twice as fast on my 16k sampled 30s audio clip.

Is that to be expected or did I do something wrong with my JAX installation?
whisper-jax takes about 10s (once cached), while faster-whisper takes 5.1s

I set the faster-whisper beam_size to 1, is there an equivalent setting for whisper-jax?

**Comment by Tronic** [comment]
Sorry to hijack this a bit, but one interesting question is whether Jax (given its objects are immutable) is able to run multiple threads in parallel (thread safety) on the same model pipeline / model weights. That could be a clear advantage for this module.

Note there is also whispercpp (C++ implementation and Python binding by that name) which could be of interest, but also runs fairly slowly (using CPU only).

With OpenAI whisper module running a single 30 second segment on RTX 3090 and large-v2 only seems to take me 200 ms, which I consider very fast (also doesn't use much VRAM). It seems to work fine for audio segments up to 30 seconds, but other implementations do overlapping 30 s segments in order to support longer files, and that slows them down a lot even if the audio would fit in a single segment.

**Comment by SinanAkkoyun** [comment]
@Tronic Thanks for the fast reply!
> With OpenAI whisper module running a single 30 second segment on RTX 3090 and large-v2 only seems to take me 200 ms, which I consider very fast (also doesn't use much VRAM). It seems to work fine for audio segments up to 30 seconds, but other implementations do overlapping 30 s segments in order to support longer files, and that slows them down a lot even if the audio would fit in a single segment.

Really? Wow, that's blazing fast. May I ask what your setup is and how did you install JAX? (also, are you running on native linux?)
Are you really telling me that the stock OpenAI/Whisper is taking you only 200ms? I once tested it on a lambdagpu A100 and got similar results to mine

**Comment by SinanAkkoyun** [comment]
@Tronic Did you do any modifications to beam size and precision etc? Mine takes up about 20GB of VRAM

**Comment by Tronic** [comment]
Using OpenAI in Python with default settings, it doesn't use much VRAM or time at all:

```python
d = torch.zeros(whisper.audio.N_SAMPLES, dtype=torch.float32)  # Must be exactly 30 seconds (audio at beginning)
model = whisper.load_model("large", device="cuda")  # This takes a couple of seconds
options = whisper.DecodingOptions(without_timestamps=True, task="translate", language="en")
mel = whisper.log_mel_spectrogram(d).to(model.device)
result = whisper.decode(model, mel, options)  # 200 ms
```

The whisper-jax module uses all my 24 GB of VRAM even on small and gives out of memory errors on medium and large models. Didn't try tuning any settings yet.

**Comment by ezerhouni** [comment]
@SinanAkkoyun I am seeing something similar on my end (up to 4x slower than faster-whisper) for small files

**Comment by SinanAkkoyun** [comment]
Thank you all for the great responses!
I really appreciate it!

**Comment by syedmustafa54** [comment]
> 

Hello @oliverwehrens  when i ran your code this got printed but never completed the results my mp3 files is about 2 sec
```
Load Model at  2023-04-24 03:19:10.960131
Loading took 0:00:16.827978
started at 2023-04-24 03:19:27.788109

```
